services:
  docsearch.webapi:
    image: docsearch.webapi
    build:
      context: .
      dockerfile: src/DocSearch.WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DocSearchDb;Username=postgres;Password=mysecretpassword
      - Gemini__ApiKey=AQ.Ab8RN6Lpalto_FEuCpXXkfEBayFoTnjyW05ZshAgFsgQdDZjzg
    volumes:
      - ./docs:/docs
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=DocSearchDb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: